### PR TITLE
chore: tweaks to fix `pnpm install`

### PR DESCRIPTION
**Pull request by colinaaa**
Some pnpm-related tweaks:

1. Upgrade to `pnpm@10.14.0`.
2. Fix `webpack@5.99.9` patch failed since we have `ignorePatchFailures: false` (the patch has been merged in https://github.com/webpack/webpack/pull/19772, so we can remove it from next webpack release).
3. Add `typescript` to the `peerDependencies` of `ts-patch` for enableGlobalVirtualStore. This would solve the "Error: Cannot find module 'typescript'" error during local `pnpm install`.
4. Remove useless overrides to `path-serializer`.

@coderabbitai summary

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).
- [ ] Changeset added, and when a BREAKING CHANGE occurs, it needs to be clearly marked (or not required).

### CODE REVIEW

File: pnpm-workspace.yaml [hunk 1]
```diff
@@ -39,12 +39,18 @@ catalogs:
 overrides:
   "@rspack/core": "$@rspack/core"
   "@rsbuild/core>@rspack/core": "$@rspack/core"
-  "path-serializer": "^0.5.0"
 
 patchedDependencies:
   "@napi-rs/cli@2.18.4": "patches/@napi-rs__cli@2.18.4.patch"
   "@rollup/plugin-typescript": "patches/@rollup__plugin-typescript.patch"
-  "webpack": patches/webpack.patch
+  "webpack@5.101.0": patches/webpack@5.101.0.patch
```
[the remark this answers is not in the document]
Comment (colinaaa) [reply pnpm-workspace.yaml:52]: This is used for fixing the patch error to webpack@5.99.9. The patch only take effect on webpack@5.100.0. Maybe we should change to webpack@^5.100.0 instead,

**Review by PupilTong — APPROVED** [review]
