### PR TITLE
fix(rspeedy/react): only enable Yarn PnP resolution when running under the PnP runtime

### LINKED ISSUE #2539: [Bug]: Cannot find module '@lynx-js/react/jsx-runtime'
### System Info

System:MacOS 26.3
node:v22.22.2
npm:10.9.7

### Details

npm run dev

> fs-test-demo@0.0.0 dev
> rspeedy dev

  Rspeedy v0.14.3 (Rsbuild v1.7.5, Rspack v1.7.11)

error   Cannot find module '@lynx-js/react/jsx-runtime'
    at file:///Users/xxxUser/projectnode_modules/@lynx-js/react-alias-rsbuild-plugin/dist/index.js:472:44
    at Object.handler (file:///Users/xxxUser/projectnode_modules/@lynx-js/react-alias-rsbuild-plugin/dist/index.js:389:21)
    at Object.callChain (file:///Users/xxxUser/projectnode_modules/@rsbuild/core/dist/131.js:2345:45)
    at async modifyBundlerChain (file:///Users/xxxUser/projectnode_modules/@rsbuild/core/dist/131.js:3733:66)
    at async generateRspackConfig (file:///Users/xxxUser/projectnode_modules/@rsbuild/core/dist/131.js:3906:251)
    at async initConfigs (file:///Users/xxxUser/projectnode_modules/@rsbuild/core/dist/131.js:4056:108)
    at async createCompiler_createCompiler (file:///Users/xxxUser/projectnode_modules/@rsbuild/core/dist/131.js:4117:84)
    at async createCompiler (file:///Users/xxxUser/projectnode_modules/@rsbuild/core/dist/131.js:7432:37)
    at async startCompile (file:///Users/xxxUser/projectnode_modules/@rsbuild/core/dist/131.js:7118:42)
    at async devServer_createDevServer (file:///Users/xxxUser/projectnode_modules/@rsbuild/core/dist/131.js:7252:37)

### Reproduce link

_No response_

### Reproduce Steps

 问题根源: @lynx-js/react-alias-rsbuild-plugin 插件中使用的 rspack ResolverFactory 在 enablePnp: true 模式下存在 bug，导致无法解析任何         
  node_modules 中的模块。           
                                                                                                                                                
  解决方案: 修改 node_modules/@lynx-js/react-alias-rsbuild-plugin/dist/index.js，将 enablePnp: true 改为 enablePnp: false。                     
                        
  让我清理测试文件。                                                                                                                            
                                   
⏺ Bash(rm -f /Users/zhaosc/Spade/fs-demo/test-*.mjs 2>&1)                                                                                       
  ⎿  Done                           
                                                                                                                                                
⏺ 问题已解决！rspeedy dev 现在可以正常运行了。              
                                                                                                                                                
  根本原因: @lynx-js/react-alias-rsbuild-plugin 插件使用的 rspack ResolverFactory 在 enablePnp: true 模式下存在 bug，导致无法解析 node_modules  
  中的任何模块。        
                                                                                                                                                
  修复方法: 在 node_modules/@lynx-js/react-alias-rsbuild-plugin/dist/index.js:467 处，将 enablePnp: true 改为 enablePnp: false。                
                        
  注意: 这是一个临时修复。npm 包修改在重新安装依赖后会丢失。建议：                                                                              
  1. 使用 patch-package 永久修复这个问题
  2. 或向 Lynx 团队报告这个 bug

### PR DESCRIPTION
**Pull request by upupming**
Fixes #2539

## Problem

`rspeedy dev` / `rspeedy build` fails with:

```
error   Cannot find module '@lynx-js/react/jsx-runtime'
    at .../@lynx-js/react-alias-rsbuild-plugin/dist/index.js
```

whenever a stray Yarn PnP manifest (`.pnp.cjs`) exists in **any ancestor directory** of an npm/pnpm project — e.g. left over from a past Yarn Berry install in `$HOME` or a parent folder.

## Root cause

`createLazyResolver` hardcodes `enablePnp: true` (introduced in #1964 to support Yarn PnP). With `enablePnp: true`, Rspack's `ResolverFactory` walks up from the resolve directory looking for a `.pnp.cjs`; once found, resolution goes through the PnP manifest **without falling back to `node_modules`**. A leftover manifest that doesn't know the project's dependencies then makes every resolution fail.

Minimal repro (reproduces on latest Rspeedy 0.15.1 / Rspack 2.0.8, not just the 0.14.3 reported in the issue):

```bash
mkdir demo && cd demo
echo '{"name":"parent-app"}' > package.json
corepack use yarn@4.9.1        # Yarn 4 defaults to the PnP linker → generates .pnp.cjs

npx -y create-rspeedy app --template react-ts
cd app && npm install
npm run build                  # ❌ Cannot find module '@lynx-js/react/jsx-runtime'
rm ../.pnp.cjs && npm run build  # ✅ works
```

Isolated to the resolver itself:

```js
import { rspack } from '@rspack/core'
const { ResolverFactory } = rspack.experiments.resolver
// with a stray .pnp.cjs in an ancestor directory:
new ResolverFactory({ conditionNames: ['import'], enablePnp: true })
  .sync(projectDir, '@lynx-js/react/jsx-runtime')   // ❌ Cannot find module
new ResolverFactory({ conditionNames: ['import'], enablePnp: false })
  .sync(projectDir, '@lynx-js/react/jsx-runtime')   // ✅ node_modules/@lynx-js/react/runtime/jsx-runtime/index.js
```

## Fix

Gate PnP on the actual runtime: `enablePnp: !!process.versions.pnp`. Real Yarn PnP projects always run build scripts through the PnP runtime (`yarn dev` / `yarn build`), which sets `process.versions.pnp`, so PnP support from #1964 is preserved; projects not running under PnP are no longer hijacked by unrelated manifests.

## Tests

`packages/rspeedy/plugin-react-alias/test/pnp.test.ts`:

- **stray manifest**: a `.pnp.cjs` (not knowing the requested package) in an ancestor of a project with `node_modules` → resolves via `node_modules`. Fails before this fix with the exact error from #2539.
- **real PnP**: with `process.versions.pnp` set and the manifest mapping the package to a PnP location (with a competing copy in `node_modules`) → resolves via the manifest, proving PnP resolution still wins under the PnP runtime.

Also verified end-to-end: applying this change to the installed plugin in the repro project above makes `rspeedy build` succeed with the stray `.pnp.cjs` still present.

## Checklist

- [x] Tests updated (or not required).
- [x] Documentation updated (or not required).
- [x] Changeset added, and when a BREAKING CHANGE occurs, it needs to be clearly marked (or not required).

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed module resolution so stray Yarn Plug’n’Play manifests in parent folders no longer affect builds unless the app is actually running in a PnP environment.
  * This helps prevent `Cannot find module '`@lynx-js/react/jsx-runtime`'` errors in non-PnP setups.

* **Tests**
  * Added coverage for both PnP and non-PnP resolution behavior to prevent regressions.

### CODE REVIEW

**Comment by upupming** [comment]
The remaining CI failures are unrelated to this PR:

- **test-rstest**: pre-existing breakage on `main` — d7a98bd8f (#2898) changed the scroll-view fading-edge keyframes without regenerating the server-e2e snapshots; it only surfaces on a cold (cache-miss) build, and currently fails on every PR. Fix: #2922
- **website / build**: npm registry download `TimeoutError` (infra flakiness), will rerun.

Will rerun the failed jobs once #2922 lands.

**Review by colinaaa — APPROVED** [review]
